# Generated by Django 3.2.25 on 2024-04-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='image_url',
            new_name='image',
        ),
    ]
